export const PATRONES_INTENCION = {
  CRISIS: [
    'necesito.*ayuda.*urgente',
    'no.*puedo.*más',
    'no puedo más',
    'no quiero seguir',
    'quiero.*terminar.*todo',
    'no.*quiero.*vivir',
    'emergencia',
    'ayuda urgente',
    'me rindo',
    'no encuentro salida',
    'no tiene sentido',
    'quiero rendirme',
    'no.*vale.*la.*pena'
  ],
  AYUDA_EMOCIONAL: [
    'me.*siento.*mal',
    'estoy.*triste',
    'me siento triste',
    'estoy deprimido',
    'estoy deprimida',
    'necesito.*hablar',
    'ayuda.*emocional',
    'me siento solo',
    'me siento sola',
    'me siento ansioso',
    'me siento ansiosa',
    'estoy ansioso',
    'estoy ansiosa',
    'me siento estresado',
    'me siento estresada',
    'estoy estresado',
    'estoy estresada',
    'me siento preocupado',
    'me siento preocupada',
    'estoy preocupado',
    'estoy preocupada',
    'me siento abrumado',
    'me siento abrumada',
    'estoy abrumado',
    'estoy abrumada'
  ],
  CONSULTA_IMPORTANTE: [
    'necesito.*consejo',
    'que.*debo.*hacer',
    'ayuda.*decision',
    'qué hago',
    'qué debería hacer',
    'no sé qué hacer',
    'puedes aconsejarme',
    'me das un consejo',
    'me puedes ayudar con una decisión',
    'tengo una duda importante',
    'necesito orientación'
  ],
  CONVERSACION_GENERAL: [
    'hola',
    'buenos días',
    'buenas tardes',
    'buenas noches',
    'como.*estas',
    'cómo estás',
    'que.*tal',
    '¿qué tal?',
    '¿cómo va?',
    '¿cómo te va?',
    'saludos',
    'hey',
    'buen día',
    'qué pasa',
    'qué cuentas'
  ]
};

export const PATRONES_TEMA = {
  EMOCIONAL: [
    'triste(za)?',
    'deprimid(o|a)',
    'feliz',
    'alegr(ía|e)',
    'ansiedad',
    'ansios(o|a)',
    'miedo',
    'temor',
    'estres(ado|ada)?',
    'preocupad(o|a)',
    'abrumad(o|a)',
    'soledad',
    'culpa',
    'vergüenza',
    'enojo',
    'ira',
    'rabia',
    'frustración',
    'impotencia',
    'nostalgia',
    'apatía',
    'desánimo',
    'desmotivad(o|a)'
  ],
  RELACIONES: [
    'pareja',
    'relación',
    'relaciones',
    'novio',
    'novia',
    'espos(o|a)',
    'familia',
    'madre',
    'padre',
    'hij(o|a)',
    'herman(o|a)',
    'amig(o|a)',
    'amistad',
    'compañer(o|a)',
    'conflicto familiar',
    'conflicto de pareja',
    'divorcio',
    'separación',
    'pérdida',
    'duelo'
  ],
  TRABAJO_ESTUDIO: [
    'trabajo',
    'empleo',
    'oficina',
    'jefe',
    'colega',
    'compañer(o|a) de trabajo',
    'proyecto',
    'tarea',
    'estudio',
    'universidad',
    'escuela',
    'examen',
    'clase',
    'profesor',
    'maestro',
    'rendimiento',
    'estrés laboral',
    'estrés académico',
    'desempleo',
    'búsqueda de trabajo'
  ],
  SALUD: [
    'salud',
    'enfermedad',
    'dolor',
    'malestar',
    'síntoma',
    'cansancio',
    'insomnio',
    'fiebre',
    'gripe',
    'lesión',
    'hospital',
    'doctor',
    'médic(o|a)',
    'terapia',
    'tratamiento',
    'ansiedad física',
    'ataque de pánico'
  ],
  GENERAL: [
    'vida',
    'futuro',
    'presente',
    'pasado',
    'situación',
    'problema',
    'dificultad',
    'meta',
    'objetivo',
    'logro',
    'cambio',
    'rutina',
    'motivación',
    'esperanza',
    'incertidumbre',
    'decisión',
    'proyecto personal',
    'crecimiento',
    'desarrollo'
  ]
};
